In [1]:
import torch
from tensorflow.python.training import learning_rate_decay
from torch.autograd import grad

In [7]:
# Constant tensors
print(torch.ones(size=(5, 3))) # 5 samples and 3 features of a sample

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
print(torch.zeros(size=(5, 3)))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
torch.tensor([1, 2, 3], dtype=torch.float32) # must use torch. to use specific data types e.g. float32

tensor([1., 2., 3.])

In [15]:
# Random tensors
x1 = torch.autograd.Variable(torch.normal (
    mean=torch.zeros(size=(3, 1)),
    std=torch.ones(size=(3, 1)),
))
x2 = torch.randn(size=(3, 3))
print(x1)
print(x2)

tensor([[ 1.2398],
        [-0.4345],
        [-0.0535]])
tensor([[-0.4100, -2.4401, -2.2170],
        [ 0.9870, -1.9077, -0.4128],
        [ 1.0437,  1.4591, -0.1214]])


In [19]:
# Using uniform
x = torch.randn(3, 3).uniform_(-5, 5)
# Create a random tensor with the shape (3, 3) where
# the distribution is scattered anywhere between -5 and 5 (uniform)
print(x)

tensor([[-4.1793,  4.5874,  3.1744],
        [ 3.1398, -3.6846, -3.0869],
        [-0.7651, -3.3967, -4.8793]])


In [20]:
# Creating a dense layer in pytorch

def dense(inputs, W, b):
    return torch.relu(torch.matmul(inputs, W) + b)

In [22]:
# therefore a simple model...

def model(inputs, W, b):
    return torch.matmul(inputs, W) + b

def mean_squared_error(targets, predictions):
    per_sample_losses = torch.square(targets - predictions)
    return torch.mean(per_sample_losses)

learning_rate = 0.1

def training_step(inputs, targets, W, b):
    predictions = model(inputs, W, b)
    loss = mean_squared_error(targets, predictions)
    loss.backward()
    grad_loss_wrt_W, grad_loss_wrt_b = W.grad, b.grad
    with torch.no_grad():
        W -= grad_loss_wrt_W * learning_rate
        b -= grad_loss_wrt_b * learning_rate
    W.grad = None
    b.grad = None
    return loss