In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# 4 different numpy arrays train_images, train_labels, test_images, test_labels- mnist is a training set of 60,000 training images plus 10,000 test images

# train_images, train_labels = training set - the data the model will learn from
# test_images, test_labels = test set - the data that the model will be tested on

In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], shape=(10000,), dtype=uint8)

In [8]:
import keras
from keras import layers

# Building a network model
model = keras.Sequential(
    [
        layers.Dense(512, activation="relu"),   # Dense = fully connected layer
        layers.Dense(10, activation="softmax"), # softmax classification layer which returns a 10-way (summing to 1)
    ]
)

# Layer = building block of a neural network acts as a data filter
# - transforms input data through learned parameters (weights and biases)

In [9]:
# Loss function = measures model performance
# Optimiser = mechanism used to update weights to improve model's performance

model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"],
              )

In [10]:
# Preparing the image data
# Converting numpy arrays into the shape the model expects
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype("float32") / 255

In [17]:
# Fitting the model to its training data
model.fit(train_images, train_labels, epochs=5, batch_size=128)

# accuracy = correct prediction
# loss = how wrong the model is in the moment

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9925 - loss: 0.0267
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9948 - loss: 0.0201
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9959 - loss: 0.0158
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9972 - loss: 0.0119
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9976 - loss: 0.0096


In [12]:
# Using the model to make predictions using the test set

test_digits = test_images[0:10] # taking 10 test images from array
predictions = model.predict(test_digits)
predictions[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([5.4089600e-07, 3.3466009e-08, 7.0369588e-06, 1.7237378e-04,
       1.7724702e-09, 2.4527610e-06, 1.3147802e-10, 9.9976218e-01,
       6.9257374e-07, 5.4669814e-05], dtype=float32)

In [13]:
predictions[0].argmax()

np.int64(7)

In [14]:
predictions[0][7]

np.float32(0.9997622)

In [15]:
test_labels[0]

np.uint8(7)

In [18]:
# Evaluating the model on new data
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test acc: {test_acc}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - accuracy: 0.9805 - loss: 0.0695
test acc: 0.9804999828338623


In [19]:
# Conclusion:
# 1. Model makes predictions on a batch
# 2. Loss Function compares the predictions to the true labels -> produces the loss value
# 3. Optimizer (adam) uses that loss to nudge the weights via backpropagation
# 4. Repeat for every batch